apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.seaweedfs.filer.s3.existingConfigSecret }}-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.seaweedfs.filer.s3.existingConfigSecret }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.seaweedfs.filer.s3.externalSecretKey }}
