apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ index .Values "oauth2-proxy" "config" "existingSecret" }}-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ index .Values "oauth2-proxy" "config" "existingSecret" }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ index .Values "oauth2-proxy" "config" "externalSecretKey" }}
