name: infra-storage
apiVersion: v2
version: 0.1.0
description: A Helm chart for deploying homelab storage stack
type: application
appVersion: 0.1.0
maintainers:
  - name: KarafrOrg
    email: karafra@karafra.net
keywords:
  - storage
  - s3
  - homelab
dependencies:
  - name: infra-storage-rook-ceph
    version: 0.1.0
    repository: file://./rook-ceph
  - name: infra-storage-rook-ceph-cluster
    version: v0.1.0
    repository: file://./rook-ceph-cluster
  - name: infra-storage-longhorn
    version: v0.1.0
    repository: file://./longhorn
