apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-longhorn-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-longhorn-secret
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgres-longhorn-database-user
        metadataPolicy: None
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgres-longhorn-database-password
        metadataPolicy: None
