apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: rook-ceph-object-store
spec:
  # Number of RGW instances
  gateway:
    instances: 1
    type: s3
  # Pool specs
  dataPool:
    replicated:
      size: 3
  metadataPool:
    replicated:
      size: 3
  # Optional: TLS (skip for HTTP)
  secure: false
